//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAdmin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersBig
    {
        public CustomersBig()
        {
            this.OrdersBigs = new HashSet<OrdersBig>();
        }
    
        public int ID_Customer { get; set; }
        public string Name { get; set; }
        public string Col1 { get; set; }
        public string Col2 { get; set; }
    
        public virtual ICollection<OrdersBig> OrdersBigs { get; set; }
    }
}
