//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAdmin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsBig
    {
        public int ID_Product { get; set; }
        public string Product_Name { get; set; }
        public string Col1 { get; set; }
    }
}
